# Copyright (c) 2025, Bertrand Mollinier Toublet
# See LICENSE for details of BSD 3-Clause License

CPPFLAGS = -std=c++2a -Wall -Wsign-compare -Werror -Werror=return-type -MMD -MP
# coverage=1 instruments the build so a test run records which lines and
# branches were exercised. It implies an unoptimized, debuggable build (-O3
# would fold branches together and make the line mapping unreliable) and adds
# '--coverage' to both compile and link, so it takes precedence over debug=1.
# Both gcc and clang emit gcov-format .gcno/.gcda data from '--coverage', so a
# single flag covers either toolchain; gcovr reads the result. See the
# 'coverage' target/CI job and README for how to produce a report.
ifeq ($(coverage),1)
CPPFLAGS += -O0 -g --coverage
LDFLAGS += --coverage
else ifeq ($(debug),1)
CPPFLAGS += -O0 -g
else
CPPFLAGS += -O3
endif

CC = $(CXX)
LDLIBS = -ledit

# All intermediate artifacts (.o, the auto-generated .d dep files, and the
# .gcno/.gcda coverage data emitted alongside each object) land under build/ so
# the repo root holds only sources. The binary itself stays at the root: it is
# the documented entry point ('./sudoku-solver') that tests/run.sh and the docs
# invoke. build/ is gitignored wholesale.
BUILD = build

src = coord.cpp \
	  cell.cpp \
	  board.cpp \
	  analyzer.cpp \
	  analyzer-nakedsingles.cpp \
	  analyzer-hiddensingles.cpp \
	  analyzer-nakedpairs.cpp \
	  analyzer-lockedcandidates.cpp \
	  analyzer-hiddenpairs.cpp \
	  analyzer-xwing.cpp \
	  analyzer-swordfish.cpp \
	  analyzer-colorchain.cpp \
	  analyzer-ywing.cpp \
	  analyzer-xychain.cpp \
	  solverstate.cpp \
	  solver.cpp

obj = $(addprefix $(BUILD)/,sudoku-solver.o $(src:.cpp=.o))

sudoku-solver: $(obj)
	$(CXX) $(LDFLAGS) $^ $(LDLIBS) -o $@

# Compile each .cpp into build/. The order-only prerequisite on the directory
# (after the '|') creates build/ without making every object depend on its
# mtime. -MMD writes build/<name>.d next to the object; because -o names the
# full build/ path, the dependency rule it emits targets that same path.
$(BUILD)/%.o: %.cpp | $(BUILD)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

$(BUILD):
	mkdir -p $(BUILD)

.PHONY: test
test: sudoku-solver
	./tests/run.sh

# Whitebox unit tests. They link every library object (everything except the
# REPL's main, sudoku-solver.o) plus the test's own main, and reach the
# Analyzer's private members through the AnalyzerTest friend. The test source
# lives under tests/unit, so it needs -I. to find the project headers.
lib_obj = $(addprefix $(BUILD)/,$(src:.cpp=.o))
unit_bin = tests/unit/test_analyzer

.PHONY: unit
unit: $(unit_bin)
	$(unit_bin)

$(unit_bin): tests/unit/test_analyzer.cpp $(lib_obj)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -I. $^ $(LDFLAGS) -o $@

# One-shot coverage report. Rebuilds instrumented from clean, exercises both
# test suites to accumulate .gcda counts, then has gcovr render the report.
# gcovr runs gcov in its own scratch directory, so no stray .gcov files land in
# the repo root; every output (objects, data, and the report) stays in build/.
# This is the local equivalent of the 'coverage' CI job. Requires gcovr.
.PHONY: coverage
coverage:
	$(MAKE) clean
	$(MAKE) coverage=1 sudoku-solver
	./tests/run.sh
	$(MAKE) coverage=1 unit
	gcovr --root . --exclude tests --print-summary --txt -o $(BUILD)/coverage.txt
	gcovr --root . --exclude tests --html --html-details -o $(BUILD)/coverage.html
	@echo "report: $(BUILD)/coverage.txt and $(BUILD)/coverage.html"

.PHONY: clean
clean:
	rm -rf $(BUILD) sudoku-solver
	rm -f $(unit_bin) $(unit_bin).d
	rm -f tests/unit/*.gcno tests/unit/*.gcda
	rm -rf tests/unit/*.dSYM

# Header dependencies are generated automatically by the compiler: -MMD writes a
# '.d' file of #include prerequisites alongside each '.o', and -MP adds phony
# targets so a deleted header doesn't break the build. The leading '-' makes the
# include silent on the first build, before any '.d' exists. This replaces the
# old hand-maintained 'makedepend' list, which had to be regenerated by hand.
-include $(obj:.o=.d)
