# Copyright (c) 2025, Bertrand Mollinier Toublet
# See LICENSE for details of BSD 3-Clause License

CPPFLAGS = -std=c++2a -Wall -Wsign-compare -Werror -Werror=return-type -MMD -MP
ifeq ($(debug),1)
CPPFLAGS += -O0 -g
else
CPPFLAGS += -O3
endif

CC = $(CXX)
LDLIBS = -ledit

src = coord.cpp \
	  cell.cpp \
	  board.cpp \
	  analyzer.cpp \
	  analyzer-nakedsingles.cpp \
	  analyzer-hiddensingles.cpp \
	  analyzer-nakedpairs.cpp \
	  analyzer-lockedcandidates.cpp \
	  analyzer-hiddenpairs.cpp \
	  analyzer-xwing.cpp \
	  analyzer-colorchain.cpp \
	  analyzer-ywing.cpp \
	  analyzer-xychain.cpp \
	  solverstate.cpp \
	  solver.cpp

obj = sudoku-solver.o $(src:%.cpp=%.o)

sudoku-solver: $(obj)

.PHONY: test
test: sudoku-solver
	./tests/run.sh

.PHONY: clean
clean:
	rm -f $(obj) $(obj:.o=.d) sudoku-solver

# Header dependencies are generated automatically by the compiler: -MMD writes a
# '.d' file of #include prerequisites alongside each '.o', and -MP adds phony
# targets so a deleted header doesn't break the build. The leading '-' makes the
# include silent on the first build, before any '.d' exists. This replaces the
# old hand-maintained 'makedepend' list, which had to be regenerated by hand.
-include $(obj:.o=.d)
